FROM centos:7

RUN yum -y install wget unzip

RUN wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u77-b03/jdk-8u77-linux-x64.rpm" -O /tmp/jdk-8-linux-x64.rpm
RUN yum -y install /tmp/jdk-8-linux-x64.rpm
ENV JAVA_HOME /usr/java/latest

RUN wget -N https://services.gradle.org/distributions/gradle-2.12-all.zip
RUN mkdir /opt/gradle
RUN unzip gradle-2.12-all.zip -d /opt/gradle
RUN ln -sfn /opt/gradle/gradle-2.12 /opt/gradle/latest
ENV GRADLE_HOME /opt/gradle/latest

WORKDIR /var/hello-world

ENTRYPOINT ["/opt/gradle/latest/bin/gradle", "clean", "bootRun", "-PappVersion=master"]
